import { NextRequest, NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const RAILWAY_QUERY_URL = process.env.RAILWAY_QUERY_URL;
const RAILWAY_API_KEY = process.env.RAILWAY_API_KEY;

interface TweetMetric {
  id: string;
  blog_idea_id?: string;
  tweet_id: string;
  slug?: string;
  tweet_text: string;
  recorded_at: number;
  impressions: number;
  likes: number;
  retweets: number;
  replies: number;
  quotes: number;
  bookmarks: number;
  link_clicks: number;
  profile_clicks: number;
  engagement_score?: number;
  engagement_rate?: number;
}

export async function POST(request: NextRequest) {
  const key =
    request.nextUrl.searchParams.get("key") ||
    request.headers.get("x-admin-key");
  const secret = process.env.ADMIN_API_KEY;

  if (!secret || key !== secret) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json(
      { error: "ANTHROPIC_API_KEY not configured" },
      { status: 500 }
    );
  }

  // Fetch tweet metrics from Railway
  let tweets: TweetMetric[] = [];
  try {
    const body = await request.json();
    tweets = body.tweets || [];
  } catch {
    // fall through to fetch from Railway
  }

  if (tweets.length === 0 && RAILWAY_QUERY_URL) {
    try {
      const headers: Record<string, string> = {
        "Content-Type": "application/json",
      };
      if (RAILWAY_API_KEY) {
        headers["Authorization"] = `Bearer ${RAILWAY_API_KEY}`;
      }
      const res = await fetch(`${RAILWAY_QUERY_URL}/tweet-metrics/top`, {
        headers,
        signal: AbortSignal.timeout(10000),
      });
      if (res.ok) {
        const data = await res.json();
        tweets = data.tweets || [];
      }
    } catch {
      // continue with empty tweets
    }
  }

  if (tweets.length === 0) {
    return NextResponse.json(
      { error: "No tweet metrics available to analyze" },
      { status: 400 }
    );
  }

  // Format tweets for the prompt
  const tweetSummaries = tweets
    .map((t, i) => {
      const date = t.recorded_at
        ? new Date(t.recorded_at).toLocaleDateString("en-US", {
            weekday: "short",
            month: "short",
            day: "numeric",
          })
        : "unknown";
      const engRate =
        t.impressions > 0
          ? (
              ((t.likes + t.retweets + t.replies + t.link_clicks) /
                t.impressions) *
              100
            ).toFixed(2)
          : "0";
      const clickRate =
        t.impressions > 0
          ? ((t.link_clicks / t.impressions) * 100).toFixed(2)
          : "0";
      return `${i + 1}. [${date}] "${t.tweet_text?.slice(0, 280) || "N/A"}"
   Impressions: ${t.impressions} | Likes: ${t.likes} | RTs: ${t.retweets} | Replies: ${t.replies} | Link clicks: ${t.link_clicks} | Bookmarks: ${t.bookmarks} | Profile clicks: ${t.profile_clicks}
   Engagement rate: ${engRate}% | Click-through rate: ${clickRate}%`;
    })
    .join("\n\n");

  const systemPrompt = `You are an expert social media analyst specializing in X/Twitter performance for data journalism and public health content. You analyze tweet metrics to find actionable patterns.

Context: These tweets are auto-generated by a blog bot for Open Health Data Hub (openhealthdatahub.com). The bot publishes ~1 post/day across 7 public health datasets (Medicaid, Medicare, Medicare Part D, BRFSS, Medicare Inpatient, NHANES, DAC). Each blog post gets a 2-tweet thread: a hook tweet and a detail tweet with a link.

Respond with valid JSON only. No markdown fencing.`;

  const userPrompt = `Analyze these ${tweets.length} tweet performance records and return structured recommendations for improving the blog bot's tweet generation.

TWEET DATA:
${tweetSummaries}

Return this exact JSON structure:
{
  "summary": "2-3 sentence executive summary of overall performance",
  "insights": [
    {
      "category": "top_performers" | "underperformers" | "hook_style" | "click_through" | "timing" | "topic",
      "title": "Short insight title",
      "detail": "Detailed explanation with specific examples from the data",
      "examples": ["tweet text snippet 1", "tweet text snippet 2"]
    }
  ],
  "recommendations": [
    {
      "priority": "high" | "medium" | "low",
      "category": "tweet_prompt" | "article_prompt" | "topic_selection" | "persona" | "timing" | "format",
      "action": "Specific, actionable recommendation the bot should implement",
      "rationale": "Why this change would help, citing specific data"
    }
  ]
}

Include 4-8 insights and 4-8 recommendations. Focus on patterns, not individual tweets. Prioritize recommendations that would be easiest to implement in the automated pipeline.`;

  try {
    const client = new Anthropic({ apiKey });
    const response = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 4096,
      temperature: 0.3,
      system: systemPrompt,
      messages: [{ role: "user", content: userPrompt }],
    });

    const text =
      response.content[0].type === "text" ? response.content[0].text : "";

    let analysis;
    try {
      analysis = JSON.parse(text);
    } catch {
      return NextResponse.json(
        { error: "Failed to parse analysis response", raw: text },
        { status: 500 }
      );
    }

    return NextResponse.json({ analysis, tweet_count: tweets.length });
  } catch (err) {
    const message =
      err instanceof Error ? err.message : "Analysis request failed";
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
